# Polybar config (Dan Jasnowski)
# Fedora 34 / i3

[settings]
screenchange-reload = true

include-file = $HOME/.config/polybar/modules.ini

[global/wm]
margin-top = 0
margin-bottom = 0


;; COLORS
include-file = $HOME/.config/polybar/colors.ini

[bar/main]
monitor = ${env:MONITOR:HDMI-0}
include-file = $HOME/.config/polybar/bar.ini

;; MODULES ALIGNMENT
modules-left = i3 filesystem 
modules-center = weather date
modules-right = pulseaudio memory cpu temperature
# wired-network [modules-right]

scroll-up = #i3.next
scroll-down = #i3.prev

[bar/bottom]
monitor = ${env:MONITOR:HDMI-0}
include-file = $HOME/.config/polybar/bar.ini
bottom = true

modules-left = spotify
modules-center =
modules-right = docker gpu disk-io load ping network bluetooth

[bar/topright]
monitor = ${env:MONITOR:DP-0}
include-file = $HOME/.config/polybar/bar.ini

modules-left = i3
modules-center = weather date
modules-right = memory_bar

; vim:ft=dosini
