; format-preix = " "

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather.sh
interval = 300
format = <label>
label = %output%
label-font = 0
click-left = ~/.config/polybar/scripts/weather-details.sh

[module/bluetooth]
type = custom/script
exec = ~/.config/rofi-bluetooth/rofi-bluetooth --status
interval = 1
format-padding = 2
format-foreground = ${colors.fg-alt}
click-left = ~/.config/rofi-bluetooth/rofi-bluetooth &

[module/spotify]
type = custom/script
tail = true
format-prefix = "  "
format-spotify-width = 600
format = <label>
format-background = ${color.bg-alt}
format-foreground = ${color.fg-alt}
exec = ~/.config/polybar/scripts/scroll_spotify_status.sh
click-left = i3-msg '[class="Spotify"] focus'

[module/previous]
type = custom/script
interval = 86400
format = "%{T3}<label>"
format-padding = 3
; Previous song icon
exec = echo "PREV"
; Check if spotify is running before displaying the icon
exec-if = "pgrep spotify -x"
line-size = 1
click-left = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"

[module/next]
type = custom/script
interval = 86400
format = "%{T3}<label>"
format-padding = 2
; Next song icon
exec = echo "NEXT"
; Check if spotify is running before displaying the icon
exec-if = "pgrep spotify -x"
line-size = 1
click-left = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"

[module/playpause]
type = custom/ipc
hook-0 = echo ""
hook-1 = echo ""
initial = 1
click-left = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"

[module/filesystem]
type = internal/fs

; Mountpoints to display
mount-0 = /

label-mounted-padding = 1
interval = 10
fixed-values = true
spacing = 4

format-mounted = <label-mounted>

label-mounted = %mountpoint%: %percentage_used%% of %total%


[module/pulseaudio]
type = internal/pulseaudio

sink = alsa_output.pci-0000_0d_00.4.analog-stereo
format-volume = <ramp-volume><label-volume>

label-volume = %percentage:3:2%%    
label-volume-foreground = ${colors.fg-alt}
label-volume-padding = 1

use-ui-max = false
interval = 5

ramp-volume-0 = "%{T4}%{T-}"
ramp-volume-1 = "%{T4}%{T-}"
ramp-volume-2 = "%{T4}%{T-}"

label-muted = " muted"   
click-middle = blueman-manager
click-right = pavucontrol

[module/date]
type = internal/date

label-foreground = ${colors.fg-alt}

date = %b %d

; Optional time format
time = %I:%M %p (%a)

date-alt = %A (%W/52), %B %d %Y
time-alt = %H:%M:%S %Z

format =  <label>

label = %date%, %time%

[module/temperature]
type = internal/temperature
interval = 0.5

hwmon-path = /sys/class/hwmon/hwmon4/temp1_input

; Threshold temperature to display warning label (in degrees celsius)
thermal-zone = 0
base-temperature = 20
warn-temperature = 90

format = <ramp> <label>
format-padding = 1

; Warning
format-warn = <ramp> <label-warn>
format-warn-background = #ff0000
format-warn-foreground = #ffcc99
format-warn-padding = 1

label = %temperature-c%

label-warn = "%temperature-c%"

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

label-foreground = ${colors.fg-alt}

[module/i3]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = false
index-sort = true
reverse-scroll = false

fuzzy-match = true
format = <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 2
label-mode-background = #e60053

label-focused = %index%
label-focused-foreground = #ffffff
label-focused-background = ${colors.bg-alt}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-foreground = ${colors.fg-alt}
label-unfocused-padding = 2

label-visible = %index%
label-visible-background = #3f3f3f
label-visible-padding = 2

[module/memory]
type = internal/memory
interval = 1

format = <label>
label =  %{F#1eba1e}%percentage_used%%%{F-}
label-padding = 1

[module/cpu]
type = internal/cpu
interval = 0.5

format = <label>
label = %{T4}%{T-} %{F#2eba1e}%percentage%%%{F-}
label-padding = 1


[module/network]
type = custom/script
exec = ~/.config/polybar/scripts/network-status.sh
interval = 3
format = <label>
label = %output%
label-foreground = #00FF41
label-padding = 2
click-left = nm-connection-editor

[module/wired-network]
type = internal/network
interface = enp8s0

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true
interval = 3.0

; Available tags:
;   <label-connected> (default)
format-connected = <label-connected>

; Available tags:
;   <label-disconnected> (default)
format-disconnected = <label-disconnected>

; Available tags:
;   <label-connected> (default)
;   <label-packetloss>
;   <animation-packetloss>
format-packetloss = <animation-packetloss> <label-connected>

label-connected-padding = 2

; Default: %ifname% %local_ip%
label-connected =  Wired ↓%downspeed% ↑%upspeed%
label-connected-foreground = #00FF41

; Default: (none)
label-disconnected =
label-disconnected-foreground = #666666

[module/wireless-network]
type = internal/network
interface = wlp7s0
interval = 3.0
accumulate-stats = true


format-connected = <ramp-signal> <label-connected>
format-disconnected = <label-disconnected>

label-connected =  %essid% ↓%downspeed% ↑%upspeed%
label-connected-foreground = #00FF41
label-connected-padding = 2

label-disconnected =  No WiFi
label-disconnected-foreground = #666666
label-disconnected-padding = 2

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-foreground = #00FF41

[module/powermenu]
type = custom/menu

expand-right = false

format-spacing = 1
format-margin = 0
format-foreground = ${colors.fg}
format-background = ${colors.bg-btn-alt}
format-padding = 2

label-open = %{T9}%{T-}
label-close = %{T9}%{T-}
label-separator = 
label-foreground = #ffcc99

; logout
; menu-0-2 = 
; menu-0-2-exec = menu-open-1

; reboot
; menu-0-0 = 
; menu-0-1-exec = echo 'menu-open-2'

; poweroff
; menu-0-0 = 
; menu-0-0-exec = echo 'menu-open-3'

; sleep
menu-0-0 = 
menu-0-0-exec = systemctl suspend

; menu-1-0-exec = poweroff
; menu-2-0-exec = reboot
; menu-4-0-exec = i3-msg exit || openbox --exit
; menu-0-0-exec = systemctl suspend


[module/memory_bar]
type = internal/memory

; Seconds to sleep between updates
; Default: 1
interval = 3

; Available tags:
;   <label> (default)
;   <bar-used>
;   <bar-free>
;   <ramp-used>
;   <ramp-free>
;   <bar-swap-used>
;   <bar-swap-free>
;   <ramp-swap-used>
;   <ramp-swap-free>
format = <label> <bar-used>

; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
;   %percentage_swap_used%
;   %percentage_swap_free%
;   %mb_swap_total%
;   %mb_swap_free%
;   %mb_swap_used%
;   %gb_swap_total%
;   %gb_swap_free%
;   %gb_swap_used%

label = RAM %gb_used%/%gb_free%

; Only applies if <bar-used> is used
bar-used-indicator =
bar-used-width = 50
bar-used-foreground-0 = #55aa55
bar-used-foreground-1 = #557755
bar-used-foreground-2 = #3d4f3d
bar-used-foreground-3 = #1f241f
bar-used-fill = ▐
bar-used-empty = ▐
bar-used-empty-foreground = #052e05

; Only applies if <ramp-used> is used
ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █

; Only applies if <ramp-free> is used
ramp-free-0 = ▁
ramp-free-1 = ▂
ramp-free-2 = ▃
ramp-free-3 = ▄
ramp-free-4 = ▅
ramp-free-5 = ▆
ramp-free-6 = ▇
ramp-free-7 = █


